using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SerialCommTestApplication
{
    public partial class Form2 : Form
    {
        private Form1 _main_form;  // Reference to the main form.

        public Form2(Form1 main_form)
        {
            // Autogenerated code for the design of the GUI
            InitializeComponent();
            this._main_form = main_form;
        }

        private void OK_Click(object sender, MouseEventArgs e)
        {
            String com_port_name = PORT_NAME_SETTING_COMBO_BOX.GetItemText(PORT_NAME_SETTING_COMBO_BOX.SelectedItem);
            String bit_rate = BIT_RATE_SETTING_COMBO_BOX.GetItemText(BIT_RATE_SETTING_COMBO_BOX.SelectedItem);
            String parity = PARITY_SETTING_COMBO_BOX.GetItemText(PARITY_SETTING_COMBO_BOX.SelectedItem);
            String stop_bits = STOP_BITS_SETTING_COMBO_BOX.GetItemText(STOP_BITS_SETTING_COMBO_BOX.SelectedItem);
            String data_bits = DATA_BITS_SETTING_COMBO_BOX.GetItemText(DATA_BITS_SETTING_COMBO_BOX.SelectedItem);
            String read_timeout = READ_TIMEOUT_SETTING_TEXT_BOX.Text;
            String write_timeout = WRITE_TIMEOUT_SETTING_TEXT_BOX.Text;

            if (!_main_form.myComPort.is_open())
            {
                if (_main_form.myComPort.configure_port(com_port_name, bit_rate, parity, stop_bits, data_bits, read_timeout, write_timeout))
                {
                    _main_form.listBox1.Items.Add("Port " + com_port_name + " was succesfully configured");
                    _main_form.PORT_NAME_LABEL.Text = com_port_name + ";";

                    _main_form.listBox1.Items.Add("Bit rate: " + bit_rate);
                    _main_form.BITRATE_LABEL.Text = bit_rate + ";";

                    _main_form.listBox1.Items.Add("Parity: " + parity);
                    _main_form.PARITY_LABEL.Text = parity + ";";

                    _main_form.listBox1.Items.Add("Stop bits: " + stop_bits);
                    _main_form.STOP_BITS_LABEL.Text = stop_bits + ";";

                    _main_form.listBox1.Items.Add("Data bits: " + data_bits);
                    _main_form.DATA_BITS_LABEL.Text = data_bits + ";";

                    _main_form.listBox1.Items.Add("Read timeout: " + read_timeout);
                    _main_form.READ_TIMEOUT_LABEL.Text = read_timeout + ";";

                    _main_form.listBox1.Items.Add("Write timeout: " + write_timeout);
                    _main_form.WRITE_TIMEOUT_LABEL.Text = write_timeout + ";";

                    _main_form.listBox1.Items.Add("");
                    _main_form.listBox1.TopIndex = _main_form.listBox1.Items.Count - 1;

                    _main_form.CommonVar.ConfigDone = true;
                }
                else
                {
                    _main_form.listBox1.Items.Add("Error - Port was not configured");
                    _main_form.listBox1.Items.Add("");
                    _main_form.listBox1.TopIndex = _main_form.listBox1.Items.Count - 1;
                }
            }
            else
            {
                _main_form.listBox1.Items.Add("Close the port before configuring it");
                _main_form.listBox1.Items.Add("");
                _main_form.listBox1.TopIndex = _main_form.listBox1.Items.Count - 1;
            }

            DialogResult = System.Windows.Forms.DialogResult.OK;
        }

        private void CANCEL_Click(object sender, MouseEventArgs e)
        {
            DialogResult = System.Windows.Forms.DialogResult.OK;
        }

        private void FORM2_LOAD(object sender, EventArgs e)
        {
            // Available ports:
            String[] ports = _main_form.myComPort.get_port_names();

            foreach (String port in ports)
            {
                PORT_NAME_SETTING_COMBO_BOX.Items.Add(port);
            }
            PORT_NAME_SETTING_COMBO_BOX.SelectedIndex = _main_form.CommonVar.PortNameComboBoxIndex;

            // Bit rates:
            String[] bit_rates = { "9600", "19200", "38400", "57600", "115200" };

            foreach (String bit_rate in bit_rates)
            {
                BIT_RATE_SETTING_COMBO_BOX.Items.Add(bit_rate);
            }
            BIT_RATE_SETTING_COMBO_BOX.SelectedIndex = _main_form.CommonVar.BitRateComboBoxIndex;

            // Parity:
            String[] parities = { "None", "Odd", "Even", "Mark", "Space" };

            foreach (String parity in parities)
            {
                PARITY_SETTING_COMBO_BOX.Items.Add(parity);
            }
            PARITY_SETTING_COMBO_BOX.SelectedIndex = _main_form.CommonVar.ParityComboBoxIndex;

            // Stop bits:
            String[] stop_bits = { "1", "1.5", "2" };

            foreach (String stop_bit in stop_bits)
            {
                STOP_BITS_SETTING_COMBO_BOX.Items.Add(stop_bit);
            }
            STOP_BITS_SETTING_COMBO_BOX.SelectedIndex = _main_form.CommonVar.StopBitsComboBoxIndex;

            // Data bits:
            String[] data_bits = { "8", "7", "6", "5" };

            foreach (String data_bit in data_bits)
            {
                DATA_BITS_SETTING_COMBO_BOX.Items.Add(data_bit);
            }
            DATA_BITS_SETTING_COMBO_BOX.SelectedIndex = _main_form.CommonVar.DataBitsComboBoxIndex;

            // Read timeout time:
            READ_TIMEOUT_SETTING_TEXT_BOX.Text = _main_form.CommonVar.ReadTimeoutText;

            // Write timeout time:
            WRITE_TIMEOUT_SETTING_TEXT_BOX.Text = _main_form.CommonVar.WriteTimeoutText;
        }

        private void BIT_RATE_SETTING_COMBO_BOX_SelectionChangeCommitted(object sender, EventArgs e)
        {
            _main_form.CommonVar.BitRateComboBoxIndex = BIT_RATE_SETTING_COMBO_BOX.SelectedIndex;
        }

        private void PORT_NAME_SETTING_COMBO_BOX_SelectionChangeCommitted(object sender, EventArgs e)
        {
            _main_form.CommonVar.PortNameComboBoxIndex = PORT_NAME_SETTING_COMBO_BOX.SelectedIndex;
        }

        private void PARITY_SETTING_COMBO_BOX_SelectedIndexChanged(object sender, EventArgs e)
        {
            _main_form.CommonVar.ParityComboBoxIndex = PARITY_SETTING_COMBO_BOX.SelectedIndex;
        }

        private void STOP_BITS_SETTING_COMBO_BOX_SelectedIndexChanged(object sender, EventArgs e)
        {
            _main_form.CommonVar.StopBitsComboBoxIndex = STOP_BITS_SETTING_COMBO_BOX.SelectedIndex;
        }

        private void DATA_BITS_SETTING_COMBO_BOX_SelectedIndexChanged(object sender, EventArgs e)
        {
            _main_form.CommonVar.DataBitsComboBoxIndex = DATA_BITS_SETTING_COMBO_BOX.SelectedIndex;
        }

        private void READ_TIMEOUT_SETTING_TEXT_BOX_TextChanged(object sender, EventArgs e)
        {
            _main_form.CommonVar.ReadTimeoutText = READ_TIMEOUT_SETTING_TEXT_BOX.Text;
        }

        private void WRITE_TIMEOUT_SETTING_TEXT_BOX_TextChanged(object sender, EventArgs e)
        {
            _main_form.CommonVar.WriteTimeoutText = WRITE_TIMEOUT_SETTING_TEXT_BOX.Text;
        }
    }
}
